apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
data:
  TELEGRAM_BOT_TOKEN: "{{ .Values.secret.password }}"
  API_NINJAS_KEY: "{{ .Values.secret.apiNinjasKey }}"
