name: Workflow
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  validate-renovate-config:
    uses: BlindfoldedSurgery/renovate-config/.github/workflows/validate.yml@main

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sed -i 's/python.*//' .tool-versions
      - uses: asdf-vm/actions/install@v3
      - run: jb install
      - run: tk lint environments/default

  build-container-image:
    needs:
    - lint
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-image-docker.yml@v3
    with:
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-container-image
    concurrency: production
    steps:
      - uses: actions/checkout@v4
      - run: sed -i 's/python.*//' .tool-versions
      - uses: asdf-vm/actions/install@v3
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - run: jb install
      - run: mkdir $HOME/.kube
      - run: 'echo "$KUBECONFIG_RAW" > $HOME/.kube/config'
        shell: bash
        env:
          KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW }}
      - run: |
          tk apply --auto-approve always -V "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" -V "API_NINJAS_KEY=${{ secrets.API_NINJAS_KEY }}" -V "THE_CATS_API_KEY=${{ secrets.THE_CATS_API_KEY }}" -V "NASA_API_KEY=${{ secrets.NASA_API_KEY }}" environments/default

  clean:
    concurrency: cleanup
    needs: deploy
    uses: BlindfoldedSurgery/actions-container/.github/workflows/clean.yml@v3
